/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULATOR_H_RPCGEN
#define _CALCULATOR_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct Operands {
	int op1;
	int op2;
};
typedef struct Operands Operands;

#define CALCULATOR 0x20000001
#define CALCULATOR_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define SUMAR 1
extern  double * sumar_1(Operands *, CLIENT *);
extern  double * sumar_1_svc(Operands *, struct svc_req *);
#define RESTAR 2
extern  double * restar_1(Operands *, CLIENT *);
extern  double * restar_1_svc(Operands *, struct svc_req *);
#define MULTIPLICAR 3
extern  double * multiplicar_1(Operands *, CLIENT *);
extern  double * multiplicar_1_svc(Operands *, struct svc_req *);
#define DIVIDIR 4
extern  double * dividir_1(Operands *, CLIENT *);
extern  double * dividir_1_svc(Operands *, struct svc_req *);
extern int calculator_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SUMAR 1
extern  double * sumar_1();
extern  double * sumar_1_svc();
#define RESTAR 2
extern  double * restar_1();
extern  double * restar_1_svc();
#define MULTIPLICAR 3
extern  double * multiplicar_1();
extern  double * multiplicar_1_svc();
#define DIVIDIR 4
extern  double * dividir_1();
extern  double * dividir_1_svc();
extern int calculator_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Operands (XDR *, Operands*);

#else /* K&R C */
extern bool_t xdr_Operands ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULATOR_H_RPCGEN */
