/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MY_FS_H_RPCGEN
#define _MY_FS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define MY_FS 0x20000001
#define MY_FS_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define GET_FILE 1
extern  char ** get_file_1(char **, CLIENT *);
extern  char ** get_file_1_svc(char **, struct svc_req *);
#define RELEASE_FILE 2
extern  int * release_file_1(char **, CLIENT *);
extern  int * release_file_1_svc(char **, struct svc_req *);
#define GET_STATE 3
extern  char ** get_state_1(void *, CLIENT *);
extern  char ** get_state_1_svc(void *, struct svc_req *);
extern int my_fs_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define GET_FILE 1
extern  char ** get_file_1();
extern  char ** get_file_1_svc();
#define RELEASE_FILE 2
extern  int * release_file_1();
extern  int * release_file_1_svc();
#define GET_STATE 3
extern  char ** get_state_1();
extern  char ** get_state_1_svc();
extern int my_fs_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MY_FS_H_RPCGEN */
