/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CHARACTER_SERVICE_H_RPCGEN
#define _CHARACTER_SERVICE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define CHARACTER_SERVICE 0x20000001
#define CHARACTER_SERVICE_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define CANT_CARAC_E 1
extern  int * cant_carac_e_1(char **, CLIENT *);
extern  int * cant_carac_e_1_svc(char **, struct svc_req *);
#define CANT_CARAC_SE 2
extern  int * cant_carac_se_1(char **, CLIENT *);
extern  int * cant_carac_se_1_svc(char **, struct svc_req *);
#define CANT_PALABRAS 3
extern  int * cant_palabras_1(char **, CLIENT *);
extern  int * cant_palabras_1_svc(char **, struct svc_req *);
extern int character_service_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define CANT_CARAC_E 1
extern  int * cant_carac_e_1();
extern  int * cant_carac_e_1_svc();
#define CANT_CARAC_SE 2
extern  int * cant_carac_se_1();
extern  int * cant_carac_se_1_svc();
#define CANT_PALABRAS 3
extern  int * cant_palabras_1();
extern  int * cant_palabras_1_svc();
extern int character_service_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CHARACTER_SERVICE_H_RPCGEN */
